import Link from 'next/link';
import {notFound} from 'next/navigation';
import {allTenders,meta} from '../../../lib/data';
import {tenderPath,buyerPath,typeLabels,sourceLabels} from '../../../lib/urls';
import LocalDate from '../../../components/LocalDate';
import Notice from '../../../components/Notice';
import RecordStatus from '../../../components/RecordStatus';
export const dynamicParams=false;
export function generateStaticParams(){return allTenders.map(t=>({id:`${t.source}-${t.id}`}));}
const find=(id:string)=>allTenders.find(t=>`${t.source}-${t.id}`===id);
export async function generateMetadata({params}:{params:Promise<{id:string}>}){const t=find((await params).id);return {title:t?.title??'Tender not found',description:t?.description.slice(0,155)}}
export default async function Detail({params}:{params:Promise<{id:string}>}){const t=find((await params).id);if(!t)notFound();const archived='archivedAt' in t?t.archivedAt as string:null;
 return <article className="detail"><Link className="back" href="/">← Browse tenders</Link><div className="badges"><span className="type-badge">{typeLabels[t.requestType]}</span><span>{sourceLabels[t.source]}</span><span>{t.reference??'No reference supplied'}</span>{archived&&<span className="archive-badge">Archived</span>}</div><h1>{t.title}</h1><Link className="detail-buyer" href={buyerPath(t.buyer)}>{t.buyer} →</Link>
 {t.requestType==='forward-notice'&&<p className="alert forward">Forward notice: this announces future procurement and is not open for submissions. Any listed closing date is a source notice date.</p>}{meta[t.source].status==='unavailable'&&<p className="alert">This source feed is unavailable. This record is from a previous snapshot and may be out of date.</p>}
 <RecordStatus closingAt={t.closingAt} archivedAt={archived}/><div className="detail-grid"><section><h2>Description</h2><p className="description">{t.description||'No description supplied.'}</p><h2>Categories</h2><div className="categories">{t.categories.map(c=><span key={c}>{c}</span>)}</div><h2>Recorded changes</h2>{t.changes.length?<ol className="changes">{[...t.changes].reverse().map((c,i)=><li key={i}><strong>{c.field}</strong><LocalDate iso={c.at}/><p><del>{c.from||'(empty)'}</del></p><p>{c.to||'(empty)'}</p></li>)}</ol>:<p>No amendments recorded since first collected.</p>}</section><aside className="facts"><a className="primary-link" href={t.sourceUrl} target="_blank" rel="noopener noreferrer">View original notice ↗</a><dl><dt>{t.requestType==='forward-notice'?'Source notice date':'Closing date'}</dt><dd><LocalDate iso={t.closingAt} raw={t.closingAtRaw}/></dd><dt>State</dt><dd>{t.state??'Not specified'}</dd><dt>Buyer type</dt><dd>{t.source==='austender'?'Commonwealth agency':t.buyerType?.replace('-',' ')??'Not specified'}</dd><dt>Published</dt><dd><LocalDate iso={t.publishedAt}/></dd><dt>First collected</dt><dd><LocalDate iso={t.firstSeenAt}/></dd>{archived&&<><dt>Archived</dt><dd><LocalDate iso={archived}/></dd></>}<dt>Specification documents</dt><dd>{t.documentCount??'Not specified'} · available at source</dd><dt>Contact</dt><dd>{t.contact?<><p>{t.contact.name}</p>{t.contact.email&&<p>{t.contact.email}</p>}{t.contact.phone&&<p>{t.contact.phone}</p>}<small>{t.contact.raw}</small></>:'Not disclosed'}</dd></dl></aside></div><Notice/></article>}
