import Link from 'next/link';
import {notFound} from 'next/navigation';
import {allTenders,meta} from '../../../lib/data';
import {tenderRouteId,buyerPath,typeLabels,sourceLabels} from '../../../lib/urls';
import LocalDate from '../../../components/LocalDate';
import RecordStatus from '../../../components/RecordStatus';
import BuyerProfile from '../../../components/BuyerProfile';
export const dynamicParams=false;
export function generateStaticParams(){return allTenders.map(t=>({id:tenderRouteId(t)}));}
const find=(id:string)=>allTenders.find(t=>tenderRouteId(t)===id);
export async function generateMetadata({params}:{params:Promise<{id:string}>}){const t=find((await params).id);return {title:t?.title??'Tender not found',description:t?.description.slice(0,155)}}
export default async function Detail({params}:{params:Promise<{id:string}>}){const t=find((await params).id);if(!t)notFound();const archived='archivedAt' in t?t.archivedAt as string:null;const details=t.vendorPanelDetails;
 return <article className="detail"><Link className="back" href="/">← Browse tenders</Link><div className="badges"><span className="type-badge">{typeLabels[t.requestType]}</span><span>{sourceLabels[t.source]}</span><span>{t.reference??'No reference supplied'}</span>{archived&&<span className="archive-badge">Archived</span>}</div><h1>{t.title}</h1><Link className="detail-buyer" href={buyerPath(t.buyer)}>{t.buyer} →</Link>
 {t.requestType==='forward-notice'&&<p className="alert forward">Forward notice: this announces future procurement and is not open for submissions. Any listed closing date is a source notice date.</p>}{meta[t.source].status==='unavailable'&&<p className="alert">This source feed is unavailable. This record is from a previous snapshot and may be out of date.</p>}
 <RecordStatus closingAt={t.closingAt} archivedAt={archived}/><div className="detail-grid"><section className="detail-content"><BuyerProfile buyer={t.buyer} details={details}/><section className="detail-section"><h2>About this opportunity</h2><p className="description">{t.description||'No description supplied.'}</p></section>
 {details?.background&&<section className="detail-section"><h2>Background</h2><p className="description">{details.background}</p></section>}
 {details?.desiredOutcomes&&<section className="detail-section"><h2>Desired outcomes and requirements</h2><p className="description">{details.desiredOutcomes}</p></section>}
 {!!details?.buyerQuestions.length&&<section className="detail-section"><h2>Questions from the buyer</h2><ol className="buyer-questions">{details.buyerQuestions.map((question,i)=><li key={i}>{question}</li>)}</ol></section>}
 {!!details?.publicQuestions.length&&<section className="detail-section"><h2>Public questions and answers</h2><div className="qa-list">{details.publicQuestions.map((item,i)=><article key={i}><div className="qa-meta">Question {item.askedAt&&<LocalDate iso={item.askedAt}/>}</div><p>{item.question}</p>{item.answer&&<div className="qa-answer"><div className="qa-meta">Buyer answer {item.answeredAt&&<LocalDate iso={item.answeredAt}/>}</div><p>{item.answer}</p></div>}</article>)}</div></section>}
 {!!details?.updates.length&&<section className="detail-section"><h2>Updates from the buyer</h2><ol className="update-list">{[...details.updates].reverse().map((item,i)=><li key={i}>{item.at&&<LocalDate iso={item.at}/>}<p>{item.description}</p></li>)}</ol></section>}
 {!!details?.serviceRegions.length&&<section className="detail-section"><h2>Regions of service</h2><div className="categories">{details.serviceRegions.map(region=><span key={region}>{region}</span>)}</div></section>}
 <section className="detail-section"><h2>Categories</h2><div className="categories">{t.categories.map(c=><span key={c}>{c}</span>)}</div></section>
 <details className="change-history"><summary>Recorded changes ({t.changes.length})</summary>{t.changes.length?<ol className="changes">{[...t.changes].reverse().map((c,i)=><li key={i}><strong>{c.field}</strong><LocalDate iso={c.at}/><p><del>{c.from||'(empty)'}</del></p><p>{c.to||'(empty)'}</p></li>)}</ol>:<p>No amendments recorded since first collected.</p>}</details></section>
 <aside className="facts"><a className="primary-link" href={t.sourceUrl} target="_blank" rel="noopener noreferrer">View original notice ↗</a><dl><dt>Contact</dt><dd>{t.contact?<>{t.contact.name&&<p>{t.contact.name}</p>}{t.contact.email&&<p>{t.contact.email}</p>}{t.contact.phone&&<p>{t.contact.phone}</p>}{!t.contact.name&&!t.contact.email&&!t.contact.phone&&t.contact.raw&&<p>{t.contact.raw}</p>}</>:'Not disclosed'}</dd>{details?.buyerReference&&<><dt>Buyer reference</dt><dd>{details.buyerReference}</dd></>}<dt>{t.requestType==='forward-notice'?'Source notice date':'Closing date'}</dt><dd><LocalDate iso={t.closingAt} raw={t.closingAtRaw}/></dd>{details?.opensAt&&<><dt>Opens</dt><dd><LocalDate iso={details.opensAt} raw={details.opensAtRaw}/></dd></>}{details?.queryCutoffAt&&<><dt>Supplier questions close</dt><dd><LocalDate iso={details.queryCutoffAt} raw={details.queryCutoffAtRaw}/></dd></>}{details?.expectedDecisionAt&&<><dt>Expected decision</dt><dd><LocalDate iso={details.expectedDecisionAt} raw={details.expectedDecisionAtRaw}/></dd></>}<dt>State</dt><dd>{t.state??'Not specified'}</dd><dt>Buyer type</dt><dd>{t.source==='austender'?'Commonwealth agency':t.buyerType?.replace('-',' ')??'Not specified'}</dd><dt>Published</dt><dd><LocalDate iso={t.publishedAt}/></dd><dt>First collected</dt><dd><LocalDate iso={t.firstSeenAt}/></dd>{archived&&<><dt>Archived</dt><dd><LocalDate iso={archived}/></dd></>}<dt>Specification documents</dt><dd>{t.documentCount??'Not specified'} · available at source</dd></dl></aside></div></article>}
